-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgbWszTBi8oLe6MLdW
dQLrLnORuIkTZQ5cVIG1OD0ScgKgCgYIKoZIzj0DAQehRANCAATh137oL1n5vspu
ZlsunHvc47E6ZT9JOPvuqKNhNwAk6UG+/pIRCSxb6+mhdHXPjm9Eoqv/lxZyCKmd
FqbggWxB
-----END PRIVATE KEY-----