# fly.toml app configuration file generated for wallet-app-backend on 2025-08-26T15:27:41-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'wallet-app-backend'
primary_region = 'lax'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 2
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
